#!/usr/bin/env zsh
# shellcheck=bash
# Copyright (c) 2016-2021 Ivan J. <parazyd@dyne.org>
# This file is part of vm-sdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.

arch="amd64"
size=20479
imageformat="qcow2"
#imageformat=raw

parted_type="dos"
dos_boot="ext4 2048s 264191s"
dos_root="ext4 264192s 100%"
bootfs="ext4"
rootfs="ext4"

PATH="$PATH:/usr/sbin:/sbin"

# Comment if you wish to disable stage4 archives for faster rebuilding
CPIO_STAGE4=1

# Comment if you wish to disable image compression
COMPRESS_IMAGE=1

# extra_packages for all images
extra_packages+=(fake-hwclock busybox-static ntp grub-pc)

case "$arch" in
i386)  extra_packages+=(linux-image-686) ;;
amd64) extra_packages+=(linux-image-amd64) ;;
esac
