#!/usr/bin/env zsh
# Copyright (c) 2016-2017 Dyne.org Foundation
# vm-sdk is written and maintained by Ivan J. <parazyd@dyne.org>
#
# This file is part of vm-sdk
#
# This source code is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this source code. If not, see <http://www.gnu.org/licenses/>.


## vm-sdk configuration
## ---------------------

arch=amd64
size=1891

PATH="$PATH:/usr/sbin:/sbin"

## options for `make` when building kernel
MAKEOPTS="-j$(expr $(grep -c 'processor' /proc/cpuinfo) + 1)"

## extra_packages for all images
extra_packages+=(fake-hwclock busybox-syslogd busybox-static openntpd)
extra_packages+=(fbterm)

purge_packages+=(rsyslog)
