#!/usr/bin/env zsh


scope=vm-sdk

SDK_LIB=../libdevuansdk
SDK_BLENDS=../devuan-sdk-blends

pushd  $SDK_LIB
source libdevuansdk
popd

pushd $SDK_BLENDS
source $SDK_BLENDS/

source
R=`pwd`
H=`pwd`
E=`pwd`


vm_sdk_init(){

	fn vm_sdk_init $@

	project_file=${1:-projects/devuan-jessie-latest-amd64-qcow2}
	act "$scope: using project file ::1 file:: " ${project_file}
	source ${project_file}
	sdk_init
}

vm_sdk_init

# example workflow:

# 1st stage
bootstrap amd64
kernel_x86_install_default

# 2nd stage
blend #install opennebula.deb

# 3rd stage
#qemu_make_img
